seed: 29
dataset:
  root: /n/netscratch/qianqian_lab/Lab/mwakeham/objaverse-oa
  manifest: generated_data/samples_full_surface.jsonl
  split_file: generated_data/splits.json
  split: train
touch:
  source: full_surface
